import Head from "next/head";

import Videopage from "../components/VideoPage";
import { useRouter } from "next/router";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/youtube.ico" />
      </Head>
      <Videopage />
    </div>
  );
}
